// <auto-generated />
namespace Veidibokin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _catch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_catch));
        
        string IMigrationMetadata.Id
        {
            get { return "201505131554476_catch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
